### ISSUE TITLE
Module doesn't work in Electron

### ISSUE THREAD

**Issue by aleksey-hoffman** [ktrongnhan/xxhash-addon#13]
Good day @ktrongnhan. I have an Electron project (created from [this boilerplate](https://github.com/nklayman/vue-cli-plugin-electron-builder)). I get the following error when trying to require this module:

```
const { XXHash3 } = require('xxhash-addon')
```
```
./node_modules/xxhash-addon/xxhash-addon.js
Module not found: Error: Can't resolve './build/Release/addon' in 'C:\PROJECT_PATH\node_modules\xxhash-addon'
```

I'm using a few other modules with native dependencies and they work just fine, so I'm not sure what the problem is with this module. 

It gets built successfully as well:
```
success Saved 1 new dependency.
info Direct dependencies
└─ xxhash-addon@1.3.0
info All dependencies
└─ xxhash-addon@1.3.0
$ electron-builder install-app-deps
  • electron-builder  version=21.2.0
  • rebuilding native dependencies  dependencies=diskusage@1.1.3, xxhash-addon@1.3.0 platform=win32 arch=x64
  • rebuilding native dependency  name=diskusage version=1.1.3
  • rebuilding native dependency  name=xxhash-addon version=1.3.0
Done in 25.20s.
```

**Comment by ktrongnhan** [comment]
Hi @aleksey-hoffman ,
First of all, I am really sorry the late reply. I got so many deadlines these days.
It is apparent from the log that the module did not build. I had a quick check using electron-webpack-quick-start and electron-builder worked well for me. I will share with your a tiny working demo with electron this weekend.
Meanwhile, could you share with me how to reproduce this with your boilerplate? Given that the boilerplate also uses electron-builder, it is strange that the module doesn't compile for you.

**Comment by aleksey-hoffman** [comment]
@ktrongnhan thank you for the reply!

I'm sorry I've spend your time with this issue. I just tried it again myself, and figured out the reason why it didn't work. I had to add this module to `externals`:

**vue.config.js**
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['chokidar', 'fsevents', 'puppeteer', 'xxhash-addon']
    }
  }
}
```

**Comment by aleksey-hoffman** [comment]
@ktrongnhan thank you for the reply!

I'm sorry I've spend your time with this issue. I just tried it again myself, and figured out the reason why it didn't work. I had to add this module to `externals`:

**vue.config.js**
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['chokidar', 'fsevents', 'puppeteer', 'xxhash-addon']
    }
  }
}
``` 
Then I restarted the dev server and it worked!
Thank you for creating this module, mate

**Comment by aleksey-hoffman** [comment]
@ktrongnhan
By the way, is there a built-in function to convert digest array to hex? Currently I'm doing it like this:

```js
// Convert Uint8Array to HEX
let hex= [...XXHash3hasher.digest()]
  .map (b => b.toString (16).padStart (2, '0'))
  .join('')
console.log(hex) // d41422dd20ea79a0
```

**Comment by ktrongnhan** [comment]
@aleksey-hoffman 
> @ktrongnhan thank you for the reply!
> 
> I'm sorry I've spend your time with this issue. I just tried it again myself, and figured out the reason why it didn't work. I had to add this module to `externals`:
> 
> **vue.config.js**
> 
> ```js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       externals: ['chokidar', 'fsevents', 'puppeteer', 'xxhash-addon']
>     }
>   }
> }
> ```
> 
> Then I restarted the dev server and it worked!
> Thank you for creating this module, mate

Nice! That's a good thing to know.



> @ktrongnhan
> By the way, is there a built-in function to convert digest array to hex? Currently I'm doing it like this:
> 
> ```js
> // Convert Uint8Array to HEX
> let hex = [...XXHash3hasher.digest()]
>   .map (b => b.toString(16).padStart(2, '0'))
>   .join('')
> console.log(hex) // d41422dd20ea79a0
> ```

There is cleaner way, you can find an example from the test https://github.com/ktrongnhan/xxhash-addon/blob/31b4efbb5c0af452b5be94171d4a96409c6056ad/xxhash-addon.test.js#L355

This uses a Buffer's built-in method https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings

**Comment by skavan** [comment]
> @ktrongnhan thank you for the reply!
> 
> I'm sorry I've spend your time with this issue. I just tried it again myself, and figured out the reason why it didn't work. I had to add this module to `externals`:
> 
> **vue.config.js**
> 
> ```js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       externals: ['chokidar', 'fsevents', 'puppeteer', 'xxhash-addon']
>     }
>   }
> }
> ```
> 
> Then I restarted the dev server and it worked!
> Thank you for creating this module, mate

I'm stuck with the same problem, using the react electron boilerplate...but can't find a place to put in that "exports" entry. Any ideas?

**Comment by aleksey-hoffman** [comment]
@skavan `externals` is the Webpack's root [property](https://webpack.js.org/configuration/externals/). So, you can put it in your webpack config file, like that:

```js
module.exports = {
  //...
  externals: [
    'xxhash-addon'
  ]
}
```
If you don't have a webpack config file, I would suggest to ask the boilerplate's creator whether the boilerplate allows you to setup webpack through some config file like `react.config.js` or something.
