### ISSUE TITLE
Update the npm build package to latest v0.8.0 ?

### ISSUE THREAD

**Issue by ORlGlN** [ktrongnhan/xxhash-addon#15]

**Comment by stychu** [comment]
+1 

Will it land sometime soon ??

**Comment by ktrongnhan** [comment]
Oops! Really sorry for the delayed update!
v0.8.0 is going to npm this Saturday.

Cheers,
Nhan

**Comment by ktrongnhan** [comment]
Done by https://github.com/ktrongnhan/xxhash-addon/pull/11
