### ISSUE TITLE
Upgrade xxhash to v0.8.2

### ISSUE THREAD

**Issue by maxime-petitjean** [ktrongnhan/xxhash-addon#32]
Last release of xxhash (https://github.com/Cyan4973/xxHash/releases/tag/v0.8.2) has some interesting optimisations and fixes, it would be great to upgrade to it!

**Comment by ktrongnhan** [comment]
@maxime-petitjean Thanks for reminding me!
Landed in v2.0.3, please run npm update to pull the new updates.
